{
 "title": "QRL node stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "avg(qrl_connections_incoming)", "legendFormat": "Incoming" },
    { "expr": "avg(qrl_connections_outgoing)", "legendFormat": "Outgoing" }
   ]
  },
  {
   "title": "Block Reward (QRL)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "avg(qrl_block_reward)", "legendFormat": "Block Reward (QRL)" }
   ]
  },
  {
   "title": "Hash power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(qrl_hashPower/100000000)", "legendFormat": "Hash power (MH/sec.)" }
   ]
  },
  {
   "title": "Difficulty",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "avg(qrl_block_difficulty)" }
   ]
  },
  {
   "title": "Block time mean",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "qrl_block_time_mean", "legendFormat": "Block time mean" }
   ]
  },
  {
   "title": "Block height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "qrl_height" }
   ]
  },
  {
   "title": "Hash Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": " MH/sec." } },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "qrl_hashPower/100000000" }
   ]
  },
  {
   "title": "Node uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": " sec." } },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "qrl_node_uptime" }
   ]
  }
 ]
}